class SimpleOrbitControls{constructor(camera,element){this.camera=camera;this.element=element;this.target=new THREE.Vector3();this.minDistance=4;this.maxDistance=20;this.dragging=false;this.last={x:0,y:0};this.didDrag=false;this.onStart=null;element.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;e.preventDefault();this.dragging=true;this.didDrag=false;this.last={x:e.clientX,y:e.clientY};this.onStart?.();element.setPointerCapture?.(e.pointerId)});element.addEventListener('pointermove',e=>{if(!this.dragging)return;const dx=e.clientX-this.last.x,dy=e.clientY-this.last.y;if(Math.abs(dx)+Math.abs(dy)>1)this.didDrag=true;this.last={x:e.clientX,y:e.clientY};const o=camera.position.clone().sub(this.target),s=new THREE.Spherical().setFromVector3(o);s.theta-=dx*.007;s.phi=Math.max(.08,Math.min(Math.PI-.08,s.phi-dy*.007));camera.position.copy(this.target).add(new THREE.Vector3().setFromSpherical(s))});const stop=()=>this.dragging=false;element.addEventListener('pointerup',stop);element.addEventListener('pointercancel',stop);element.addEventListener('lostpointercapture',stop);element.addEventListener('wheel',e=>{e.preventDefault();const o=camera.position.clone().sub(this.target),d=Math.max(this.minDistance,Math.min(this.maxDistance,o.length()*(e.deltaY>0?1.1:.9)));camera.position.copy(this.target).add(o.normalize().multiplyScalar(d))},{passive:false})}update(){this.camera.lookAt(this.target)}}
const catalog=[
 ['cuerpo','Cuerpo y bridas','#566d79','Contiene el conducto y conecta la válvula a la tubería.','Soporta la presión y guía el fluido a través del paso recto.'],
 ['asiento','Anillos de asiento','#c99448','Forman las superficies de contacto a ambos lados de la cuña.','Proporcionan el cierre estanco cuando la compuerta desciende.'],
 ['compuerta','Compuerta en cuña','#b9843d','Sube o baja perpendicularmente al flujo para abrir o cerrar.','Abierta deja el conducto libre; no está destinada a estrangular caudal.'],
 ['vastago','Vástago ascendente','#bdc8ce','Transmite el movimiento roscado del volante a la compuerta.','Su posición exterior permite reconocer el estado de apertura.'],
 ['bonete','Bonete atornillado','#667d89','Cierra la parte superior del cuerpo y guía el vástago.','Contiene la presión y permite acceso al mecanismo interno.'],
 ['empaque','Prensaestopas y empaque','#263943','Comprime el empaque alrededor del vástago.','Limita fugas hacia el exterior sin impedir el movimiento axial.'],
 ['volante','Volante y yugo','#242b30','Convierte el esfuerzo manual en giro de la tuerca del vástago.','Entrega ventaja mecánica para desplazar la cuña contra la presión.']
].map(([id,name,color,func,effect])=>({id,name,color,func,effect}));
const $=id=>document.getElementById(id),viewport=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf3f7');const camera=new THREE.PerspectiveCamera(38,1,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;viewport.append(renderer.domElement);const controls=new SimpleOrbitControls(camera,renderer.domElement);
scene.add(new THREE.HemisphereLight(0xf8fbff,0x52616b,2.2));const key=new THREE.DirectionalLight(0xffffff,3.7);key.position.set(5,8,7);scene.add(key);const fill=new THREE.DirectionalLight(0xb9ddf2,1.7);fill.position.set(-5,3,-4);scene.add(fill);const grid=new THREE.GridHelper(18,36,0xd0dce5,0xe1e8ee);grid.position.y=-2.15;grid.material.transparent=true;grid.material.opacity=.45;scene.add(grid);
const root=new THREE.Group();scene.add(root);const parts=new Map(),meshes=[],labels=[];const steel='#788d98',dark='#252c31',bronze='#b9843d',packing='#202e35';
function material(color,metal=.55,rough=.34){return new THREE.MeshPhysicalMaterial({color,metalness:metal,roughness:rough,clearcoat:.18,clearcoatRoughness:.35})}function add(g,geo,color,pos=[0,0,0],rot=[0,0,0]){const m=new THREE.Mesh(geo,material(color,color===packing?.05:.56,color===packing?.82:.34));m.position.set(...pos);m.rotation.set(...rot);g.add(m);return m}function make(id,pos,offset,draw){const g=new THREE.Group();g.name=id;g.position.set(...pos);root.add(g);draw(g);const p={...catalog.find(x=>x.id===id),group:g,home:g.position.clone(),offset:new THREE.Vector3(...offset)};parts.set(id,p);g.traverse(m=>{if(m.isMesh){m.userData.component=id;meshes.push(m)}});return g}function cyl(g,r,h,c,p=[0,0,0],axis='y',n=64){return add(g,new THREE.CylinderGeometry(r,r,h,n),c,p,axis==='z'?[Math.PI/2,0,0]:axis==='x'?[0,0,Math.PI/2]:[0,0,0])}function box(g,w,h,d,c,p=[0,0,0],r=[0,0,0]){return add(g,new THREE.BoxGeometry(w,h,d,4,4,4),c,p,r)}function torus(g,r,t,c,p=[0,0,0],axis='y'){return add(g,new THREE.TorusGeometry(r,t,14,80),c,p,axis==='y'?[Math.PI/2,0,0]:axis==='x'?[0,Math.PI/2,0]:[0,0,0])}function tube(g,outer,inner,length,color,z=0){const shape=new THREE.Shape();shape.absarc(0,0,outer,0,Math.PI*2);const hole=new THREE.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);shape.holes.push(hole);const geo=new THREE.ExtrudeGeometry(shape,{depth:length,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2,curveSegments:48});geo.translate(0,0,-length/2);return add(g,geo,color,[0,0,z])}function openPipe(g,outer,inner,length,color,z){add(g,new THREE.CylinderGeometry(outer,outer,length,64,1,true),color,[0,0,z],[Math.PI/2,0,0]);const inside=add(g,new THREE.CylinderGeometry(inner,inner,length,64,1,true),'#435965',[0,0,z],[Math.PI/2,0,0]);inside.material.side=THREE.BackSide;for(const end of [-1,1])torus(g,(outer+inner)/2,(outer-inner)/2,color,[0,0,z+end*length/2],'z')}
const body=make('cuerpo',[0,0,0],[-2.8,0,0],g=>{tube(g,1.16,.78,1.38,steel);for(const z of [-.82,.82]){tube(g,1.48,.78,.18,steel,z);for(let i=0;i<8;i++){const a=i*Math.PI/4;cyl(g,.065,.26,'#aebbc1',[1.23*Math.cos(a),1.23*Math.sin(a),z],'z',8)}}const belly=add(g,new THREE.SphereGeometry(1,64,32),steel,[0,.12,0]);belly.scale.set(1.08,.92,.78);box(g,1.35,.34,1.15,steel,[0,1.02,0]);});
make('asiento',[0,0,0],[0,-1.8,1.6],g=>{for(const z of [-.29,.29])tube(g,.82,.70,.09,bronze,z)});
const gate=make('compuerta',[0,.08,0],[0,-1.5,-2],g=>{const s=new THREE.Shape();s.moveTo(-.44,.68);s.lineTo(.44,.68);s.lineTo(.70,.38);s.lineTo(.58,-.65);s.lineTo(0,-.82);s.lineTo(-.58,-.65);s.lineTo(-.70,.38);s.closePath();const geo=new THREE.ExtrudeGeometry(s,{depth:.18,bevelEnabled:true,bevelSize:.05,bevelThickness:.04,bevelSegments:3});geo.translate(0,0,-.09);add(g,geo,bronze)});
const stem=make('vastago',[0,0,0],[1.8,2.4,0],g=>{cyl(g,.11,3.55,'#bdc8ce',[0,2.25,0]);for(let y=2.75;y<3.85;y+=.12)torus(g,.115,.012,'#899ca5',[0,y,0]);cyl(g,.19,.2,bronze,[0,.58,0])});
make('bonete',[0,0,0],[-1.8,2.1,0],g=>{const lower=cyl(g,.78,.32,steel,[0,1.25,0]);lower.scale.z=.82;const chamber=add(g,new THREE.SphereGeometry(1,64,32),steel,[0,1.73,0]);chamber.scale.set(.82,.78,.43);cyl(g,.36,.20,steel,[0,2.42,0]);for(let i=0;i<6;i++){const a=i*Math.PI/3;cyl(g,.055,.34,'#aebbc1',[.61*Math.cos(a),1.26,.46*Math.sin(a)])}});
make('empaque',[0,0,0],[1.7,1.4,1.4],g=>{cyl(g,.28,.34,packing,[0,2.15,0]);cyl(g,.40,.16,steel,[0,2.38,0]);for(const x of [-.31,.31])cyl(g,.05,.55,'#adb9bf',[x,2.45,0])});
let wheel;make('volante',[0,0,0],[2.8,2.3,0],g=>{for(const x of [-.48,.48])cyl(g,.07,1.28,steel,[x,3.05,0]);box(g,1.08,.16,.22,steel,[0,3.62,0]);wheel=new THREE.Group();wheel.position.set(0,3.95,0);g.add(wheel);torus(wheel,.88,.075,dark);cyl(wheel,.18,.13,dark);for(let i=0;i<5;i++){const a=i*Math.PI*2/5;const spoke=box(wheel,1.36,.055,.07,dark);spoke.rotation.y=a}cyl(g,.26,.32,dark,[0,3.66,0])});
const pipework=new THREE.Group();scene.add(pipework);for(const z of [-2.02,2.02]){openPipe(pipework,1.02,.78,2.25,'#8ea2ac',z);tube(pipework,1.2,.78,.13,'#6e8490',z-Math.sign(z)*1.05)}
const cutaway=new THREE.Group();scene.add(cutaway);cutaway.visible=false;for(const z of [-2.02,2.02]){const p=cyl(cutaway,1.02,2.25,'#74adc8',[0,0,z],'z');p.material.transparent=true;p.material.opacity=.22;p.material.depthWrite=false;p.material.side=THREE.DoubleSide}
const water=new THREE.Group();scene.add(water);
const waterUniforms={uTravel:{value:0},uSpeed:{value:0},uOpacity:{value:.15}};
const wm=new THREE.ShaderMaterial({uniforms:waterUniforms,transparent:true,depthWrite:false,side:THREE.DoubleSide,vertexShader:`varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){vUv=uv;vNormal=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.0);vView=-mv.xyz;gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform float uTravel;uniform float uSpeed;uniform float uOpacity;varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){float flow=vUv.y*30.0-uTravel*7.0;float wave=.5+.5*sin(flow+sin(vUv.x*19.0+uTravel*2.1));float fine=.5+.5*sin(flow*2.35-vUv.x*33.0);float caustic=smoothstep(.68,1.0,wave*.72+fine*.28);float fresnel=pow(1.0-abs(dot(normalize(vNormal),normalize(vView))),2.0);vec3 deep=vec3(.01,.28,.58),light=vec3(.26,.83,1.0);vec3 color=mix(deep,light,.18+caustic*.64+fresnel*.30);float alpha=uOpacity*(.48+caustic*.36+fresnel*.30);gl_FragColor=vec4(color,alpha);}`});
function waterSection(z,length){const group=new THREE.Group();const core=new THREE.Mesh(new THREE.CylinderGeometry(.765,.765,length,80,28,true),wm);core.rotation.x=Math.PI/2;core.renderOrder=2;group.add(core);const sheetH=new THREE.Mesh(new THREE.PlaneGeometry(1.49,length,24,80),wm);sheetH.rotation.x=Math.PI/2;sheetH.renderOrder=2;group.add(sheetH);const sheetV=new THREE.Mesh(new THREE.PlaneGeometry(length,1.49,80,24),wm);sheetV.rotation.y=Math.PI/2;sheetV.renderOrder=2;group.add(sheetV);group.position.z=z;water.add(group);return group}
waterSection(-2.05,2.3);waterSection(2.05,2.3);const bridge=new THREE.Mesh(new THREE.CylinderGeometry(.74,.74,1.7,64,24,true),wm);bridge.rotation.x=Math.PI/2;bridge.renderOrder=3;water.add(bridge);
let selected='cuerpo',mode='external',opening=0,auto=false,direction=1,fluid=false,showLabels=false,explode=0,cameraMove=null;controls.onStart=()=>cameraMove=null;
function resetCamera(){const d=mode==='explode'?13:11.2;cameraMove={target:new THREE.Vector3(0,1.15,0),position:new THREE.Vector3(8,5.2,6).normalize().multiplyScalar(d).add(new THREE.Vector3(0,1.15,0))}}
function sync(){for(const id of ['external','internal','explode'])$(id).setAttribute('aria-pressed',String(mode===id));$('view-title').textContent={external:'Conjunto con tuberías',internal:fluid?'Flujo a través del cuerpo':'Interior y mecanismo de cierre',explode:'Vista explotada · 7 componentes'}[mode];$('spin').textContent=auto?'Ⅱ Detener movimiento':opening>2?'◀ Cerrar automáticamente':'▶ Abrir automáticamente';$('fluid-toggle').textContent=fluid?'≈ Ocultar agua':'≈ Mostrar agua';$('fluid-toggle').setAttribute('aria-pressed',String(fluid));$('labels-toggle').textContent=showLabels?'⌖ Ocultar etiquetas':'⌖ Mostrar etiquetas';$('opening-value').value=Math.round(opening);$('status').textContent=`Compuerta ${Math.round(opening)}% · ${opening===0?'válvula cerrada':opening===100?'válvula abierta':'posición intermedia'}`;pipework.visible=mode==='external';cutaway.visible=mode==='internal';water.visible=fluid&&mode!=='explode';drawKv()}
function select(id,focus=true){selected=id;const p=parts.get(id);p.group.visible=true;for(const [key,item] of parts){item.group.traverse(m=>{if(m.isMesh&&m.material.emissive){m.material.emissive.set(key===id?0x6f390c:0);m.material.emissiveIntensity=key===id?.2:0}});item.button.setAttribute('aria-pressed',String(key===id))}$('part-name').textContent=p.name;$('part-function').textContent=p.func;$('part-effect').textContent=p.effect;$('part-number').textContent=String(catalog.findIndex(x=>x.id===id)+1).padStart(2,'0')+' / 07';if(focus){const box3=new THREE.Box3().setFromObject(p.group),target=box3.getCenter(new THREE.Vector3());cameraMove={target,position:target.clone().add(new THREE.Vector3(3,2.5,3).normalize().multiplyScalar(Math.max(4,box3.getSize(new THREE.Vector3()).length()*1.55)))}}sync()}
for(const [i,data] of catalog.entries()){const p=parts.get(data.id),button=document.createElement('button');button.className='part-row';button.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><span class="dot" style="background:${data.color}"></span><span>${data.name}</span><span class="arrow">›</span>`;button.onclick=()=>select(data.id);$('parts-list').append(button);p.button=button;const label=document.createElement('button');label.className='part-label';label.textContent=data.name;label.hidden=true;label.onclick=()=>select(data.id);$('labels').append(label);p.label=label;labels.push(p)}
function setMode(next){mode=next;for(const p of parts.values())p.group.visible=true;resetCamera();sync()}for(const id of ['external','internal','explode'])$(id).onclick=()=>setMode(id);$('assemble').onclick=()=>setMode('external');$('reset').onclick=resetCamera;$('opening').oninput=e=>{opening=Number(e.target.value);auto=false;sync()};$('spin').onclick=()=>{if(!auto){direction=opening>2?-1:1;if(direction>0){fluid=true;mode='internal';resetCamera()}}auto=!auto;sync()};$('fluid-toggle').onclick=()=>{fluid=!fluid;if(fluid){mode='internal';resetCamera()}sync()};$('labels-toggle').onclick=()=>{showLabels=!showLabels;sync()};$('size-select').onchange=drawKv;$('visibility').onclick=()=>{const p=parts.get(selected);p.group.visible=!p.group.visible;$('visibility').textContent=p.group.visible?'Ocultar pieza':'Mostrar pieza'};$('show-all').onclick=()=>{for(const p of parts.values())p.group.visible=true;$('visibility').textContent='Ocultar pieza'};
renderer.domElement.addEventListener('pointerup',e=>{if(controls.didDrag)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes,false)[0];if(hit)select(hit.object.userData.component,false)});
function drawKv(){const size=+$('size-select').value,kv=gateCatalog.kv[size],sizes=Object.keys(gateCatalog.kv).map(Number),canvas=$('kv-chart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height,L=72,R=24,T=38,B=58,max=110,x=i=>L+(i+.5)*(w-L-R)/sizes.length,y=v=>h-B-v/max*(h-T-B),barW=(w-L-R)/sizes.length*.58;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0c2940';ctx.fillRect(0,0,w,h);ctx.font='20px Segoe UI';for(const tick of [0,20,40,60,80,100]){ctx.strokeStyle='#35566b';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(L,y(tick));ctx.lineTo(w-R,y(tick));ctx.stroke();ctx.fillStyle='#bdd3df';ctx.textAlign='right';ctx.fillText(tick.toLocaleString('es'),L-8,y(tick)+6)}sizes.forEach((dn,i)=>{const value=gateCatalog.kv[dn],selected=dn===size;ctx.fillStyle=selected?'#ffc86c':'#58c8f2';ctx.fillRect(x(i)-barW/2,y(value),barW,h-B-y(value));ctx.textAlign='center';ctx.fillStyle=selected?'#ffc86c':'#d6e9f4';ctx.font=selected?'bold 20px Segoe UI':'20px Segoe UI';ctx.fillText(value.toLocaleString('es'),x(i),y(value)-8);ctx.fillStyle='#bdd3df';ctx.font='19px Segoe UI';ctx.fillText(`DN ${dn}`,x(i),h-29)});ctx.fillStyle='#d6e9f4';ctx.textAlign='left';ctx.font='20px Segoe UI';ctx.fillText('Kv [(m³/h)/√(ΔP)]',L,24);ctx.textAlign='center';ctx.fillText('Tamaño nominal',(L+w-R)/2,h-4);$('kv-value').value=kv.toLocaleString('es');$('kv-reading').textContent=`DN ${size} · Kv = ${kv.toLocaleString('es')} (m³/h)/√(ΔP) · totalmente abierta`;canvas.setAttribute('aria-label',`${$('kv-reading').textContent}. Comparación de valores Kv de catálogo por diámetro nominal.`)}
const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const dt=clock.getDelta();if(auto){opening+=dt*10*direction;if(opening>=100||opening<=0){opening=Math.max(0,Math.min(100,opening));auto=false}$('opening').value=opening;sync()}const lift=opening/100*1.5,openness=Math.max(0,opening/100);wheel.rotation.y+=auto?dt*direction*5:0;bridge.visible=openness>.015;bridge.scale.x=bridge.scale.y=.08+.92*openness;waterUniforms.uSpeed.value=openness;waterUniforms.uOpacity.value=.12+.09*openness;waterUniforms.uTravel.value+=dt*2.0*openness;const target=mode==='explode'?1:0;explode+=(target-explode)*dt*5;for(const p of parts.values())p.group.position.copy(p.home).addScaledVector(p.offset,explode);gate.position.y+=lift;stem.position.y+=lift;const bonnet=parts.get('bonete').group;if(mode==='internal'){body.visible=false;bonnet.visible=false}else{body.visible=true;bonnet.visible=true}for(const p of labels){p.label.hidden=!showLabels||!p.group.visible;const v=p.group.getWorldPosition(new THREE.Vector3()).project(camera);p.label.style.left=`${(v.x*.5+.5)*100}%`;p.label.style.top=`${(-v.y*.5+.5)*100}%`}if(cameraMove){camera.position.lerp(cameraMove.position,Math.min(1,dt*4));controls.target.lerp(cameraMove.target,Math.min(1,dt*4));if(camera.position.distanceTo(cameraMove.position)<.02)cameraMove=null}controls.update();renderer.setSize(viewport.clientWidth,viewport.clientHeight,false);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.render(scene,camera)}
resetCamera();camera.position.copy(cameraMove.position);controls.target.copy(cameraMove.target);cameraMove=null;select('cuerpo',false);$('loading').remove();animate();
