class SimpleOrbitControls {
  constructor(camera, element) {
    this.camera=camera;this.element=element;this.target=new THREE.Vector3();this.minDistance=3;this.maxDistance=18;this.dragging=false;this.last={x:0,y:0};
    element.addEventListener('pointerdown',e=>{this.dragging=true;this.last={x:e.clientX,y:e.clientY};element.setPointerCapture(e.pointerId);});
    element.addEventListener('pointermove',e=>{if(!this.dragging)return;const dx=e.clientX-this.last.x,dy=e.clientY-this.last.y;this.last={x:e.clientX,y:e.clientY};const offset=camera.position.clone().sub(this.target),s=new THREE.Spherical().setFromVector3(offset);s.theta-=dx*.006;s.phi=Math.max(.12,Math.min(Math.PI-.12,s.phi-dy*.006));camera.position.copy(this.target).add(new THREE.Vector3().setFromSpherical(s));});
    element.addEventListener('pointerup',()=>this.dragging=false);
    element.addEventListener('wheel',e=>{e.preventDefault();const offset=camera.position.clone().sub(this.target),distance=Math.max(this.minDistance,Math.min(this.maxDistance,offset.length()*(e.deltaY>0?1.1:.9)));camera.position.copy(this.target).add(offset.normalize().multiplyScalar(distance));},{passive:false});
  }
  update(){this.camera.lookAt(this.target);}
}

const catalog=[
 ['cuerpo','Cuerpo y bridas','#285879','Aloja el disco y conecta la válvula con la tubería mediante sus bridas.','Su geometría define el paso nominal y soporta la presión de la línea.'],
 ['disco','Disco perfilado','#0879b4','Gira dentro del cuerpo para interrumpir o permitir el paso del fluido.','Su perfil redondeado y su ángulo determinan el área disponible y la pérdida de carga.'],
 ['eje','Eje de maniobra','#aebbc3','Dos semiejes laterales transmiten el giro y apoyan el disco; los resaltes azules representan su encapsulado.','Mantiene el disco alineado durante la operación.'],
 ['asiento','Asiento elastomérico','#263942','Sella contra el borde del disco cuando la válvula está cerrada.','Reduce fugas y protege el cuerpo de contacto directo.'],
 ['cuello','Soporte lateral del eje','#315b72','Une lateralmente el cuerpo con la caja de accionamiento y guía el semieje.','Mantiene el accionamiento alineado con el eje horizontal del disco.'],
 ['palanca','Mecanismo biela-manivela','#e69a43','Convierte el movimiento del volante en el giro de cuarto de vuelta del eje.','Permite una apertura progresiva con menor esfuerzo de accionamiento.'],
 ['pernos','Pernos de brida','#98a7b0','Fijan la válvula entre las bridas de la tubería.','Mantienen la unión mecánica y la estanqueidad de las juntas.']
].map(([id,name,color,func,effect])=>({id,name,color,func,effect}));
const $=id=>document.getElementById(id), viewport=$('viewport');
const scene=new THREE.Scene();scene.background=new THREE.Color('#edf3f7');
const camera=new THREE.PerspectiveCamera(40,1,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;viewport.append(renderer.domElement);
const controls=new SimpleOrbitControls(camera,renderer.domElement);controls.minDistance=3;controls.maxDistance=18;
scene.add(new THREE.HemisphereLight(0xf4f9ff,0x586979,2));const light=new THREE.DirectionalLight(0xffffff,3.5);light.position.set(5,6,7);scene.add(light);const fill=new THREE.DirectionalLight(0xd7ecff,1.5);fill.position.set(-5,2,-4);scene.add(fill);const rim=new THREE.DirectionalLight(0x8fcfff,1.2);rim.position.set(0,4,-6);scene.add(rim);
const grid=new THREE.GridHelper(16,32,0xd0dce5,0xe1e8ee);grid.position.y=-2.1;grid.material.transparent=true;grid.material.opacity=.45;scene.add(grid);
const root=new THREE.Group();
scene.add(root);
const parts=new Map(), meshes=[], labels=[];
const blue='#0879b4',steel='#afbbc3',dark='#223c50',orange='#d59a43',rubber='#18252e';
function mat(color,metal=.45,rough=.35){return new THREE.MeshPhysicalMaterial({color,metalness:metal,roughness:rough,clearcoat:color===blue?.48:.12,clearcoatRoughness:.28});}function add(g,geo,color,pos=[0,0,0],rot=[0,0,0]){const m=new THREE.Mesh(geo,mat(color,color===rubber?.03:color===blue?.12:.55,color===rubber?.82:.3));m.position.set(...pos);m.rotation.set(...rot);g.add(m);return m;}
function make(id,pos,offset,draw){const g=new THREE.Group();g.name=id;g.position.set(...pos);root.add(g);draw(g);const p={...catalog.find(x=>x.id===id),group:g,home:g.position.clone(),offset:new THREE.Vector3(...offset)};parts.set(id,p);g.traverse(m=>{if(m.isMesh){m.userData.component=id;meshes.push(m);}});return g;}
function tube(g,outer,inner,length,color,z=0){const shape=new THREE.Shape();shape.absarc(0,0,outer,0,Math.PI*2);const hole=new THREE.Path();hole.absarc(0,0,inner,0,Math.PI*2,true);shape.holes.push(hole);const geo=new THREE.ExtrudeGeometry(shape,{depth:length,bevelEnabled:true,bevelSize:.025,bevelThickness:.025,bevelSegments:2,curveSegments:48});geo.translate(0,0,-length/2);return add(g,geo,color,[0,0,z]);}
function openPipe(g,outer,inner,length,color,z=0){const outerWall=add(g,new THREE.CylinderGeometry(outer,outer,length,64,1,true),color,[0,0,z],[Math.PI/2,0,0]);const innerWall=add(g,new THREE.CylinderGeometry(inner,inner,length,64,1,true),'#526a78',[0,0,z],[Math.PI/2,0,0]);innerWall.material.side=THREE.BackSide;for(const end of [-1,1])add(g,new THREE.TorusGeometry((outer+inner)/2,(outer-inner)/2,12,64),color,[0,0,z+end*length/2]);return outerWall;}
function bolt(g,x,y,z){add(g,new THREE.CylinderGeometry(.075,.075,.16,6),steel,[x,y,z],[Math.PI/2,0,0]);}
const pipework=new THREE.Group();pipework.name='tuberias';scene.add(pipework);
for(const side of [-1,1]){
  openPipe(pipework,1.17,1.04,2.65,'#879daa',side*1.88);
  tube(pipework,1.31,1.04,.16,'#738c9b',side*.72);
  add(pipework,new THREE.TorusGeometry(1.18,.026,12,64),'#566d7a',[0,0,side*1.02]);
  add(pipework,new THREE.TorusGeometry(1.18,.018,10,64),'#b9c8cf',[0,0,side*3.16]);
}
const pipeCutaway=new THREE.Group();pipeCutaway.name='tuberias-corte';scene.add(pipeCutaway);pipeCutaway.visible=false;
for(const side of [-1,1]){
  const shell=add(pipeCutaway,new THREE.CylinderGeometry(1.17,1.17,2.65,64,1,true,0,Math.PI*2),'#86b8cf',[0,0,side*1.88],[Math.PI/2,0,0]);
  shell.material.transparent=true;shell.material.opacity=.28;shell.material.depthWrite=false;shell.material.side=THREE.DoubleSide;
}
const catalogValve=buildCatalogValve({THREE,make,add,tube});
const {disc,shaft,handle}=catalogValve;
const flangeGhosts=new THREE.Group();scene.add(flangeGhosts);flangeGhosts.visible=false;
for(const z of [-.48,.48]){const ghost=add(flangeGhosts,new THREE.RingGeometry(1.17,1.82,96),blue,[0,0,z]);ghost.material.transparent=true;ghost.material.opacity=.18;ghost.material.depthWrite=false;ghost.material.side=THREE.DoubleSide;}
let selected='cuerpo',mode='external',opening=0,auto=false,autoDirection=1,fluid=false,showLabels=false,explode=0,cameraMove=null;
const fluidGroup=new THREE.Group();scene.add(fluidGroup);fluidGroup.visible=false;
const waterUniforms={uTravel:{value:0},uSpeed:{value:0},uOpacity:{value:.13}};
const waterMaterial=new THREE.ShaderMaterial({uniforms:waterUniforms,transparent:true,depthWrite:false,side:THREE.DoubleSide,vertexShader:`varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){vUv=uv;vNormal=normalize(normalMatrix*normal);vec4 mv=modelViewMatrix*vec4(position,1.0);vView=-mv.xyz;gl_Position=projectionMatrix*mv;}`,fragmentShader:`uniform float uTravel;uniform float uSpeed;uniform float uOpacity;varying vec2 vUv;varying vec3 vNormal;varying vec3 vView;void main(){float p=vUv.y*28.0-uTravel*7.0;float wave=.5+.5*sin(p+sin(vUv.x*18.0+uTravel*2.0));float fine=.5+.5*sin(p*2.3-vUv.x*31.0);float caustic=smoothstep(.70,1.0,wave*.72+fine*.28);float fresnel=pow(1.0-abs(dot(normalize(vNormal),normalize(vView))),2.0);vec3 deep=vec3(.015,.32,.58),light=vec3(.28,.82,1.0);vec3 color=mix(deep,light,.20+caustic*.62+fresnel*.28);float alpha=uOpacity*(.48+caustic*.34+fresnel*.30);gl_FragColor=vec4(color,alpha);}`});
function waterSection(z,length){const group=new THREE.Group();const core=new THREE.Mesh(new THREE.CylinderGeometry(1.025,1.025,length,96,28,true),waterMaterial);core.rotation.x=Math.PI/2;core.renderOrder=1;group.add(core);const sheetH=new THREE.Mesh(new THREE.PlaneGeometry(2.02,length,28,96),waterMaterial);sheetH.rotation.x=Math.PI/2;sheetH.renderOrder=1;group.add(sheetH);const sheetV=new THREE.Mesh(new THREE.PlaneGeometry(length,2.02,96,28),waterMaterial);sheetV.rotation.y=Math.PI/2;sheetV.renderOrder=1;group.add(sheetV);group.position.z=z;fluidGroup.add(group);return group;}
const waterUpstream=waterSection(-1.78,2.92),waterDownstream=waterSection(1.78,2.92);
const waterPassages=[];for(const side of [-1,1]){const bridge=new THREE.Mesh(new THREE.CylinderGeometry(1,1,1,48,12,true),waterMaterial);bridge.rotation.x=Math.PI/2;bridge.renderOrder=2;bridge.userData.side=side;fluidGroup.add(bridge);waterPassages.push(bridge);}
function resetCamera(){const d=mode==='explode'?11.5:9.7;cameraMove={target:new THREE.Vector3(0,.38,0),position:new THREE.Vector3(8,4.2,5).normalize().multiplyScalar(d).add(new THREE.Vector3(0,.38,0))};}
function sync(){for(const id of ['external','internal','explode'])$(id).setAttribute('aria-pressed',String(mode===id));$('view-title').textContent={external:'Conjunto con tuberías',internal:fluid?'Agua continua en la tubería':'Bridas y tubería transparentes · sin corte',explode:'Vista explotada · 7 componentes'}[mode];$('spin').textContent=auto?'Ⅱ Detener movimiento':opening>2?'◀ Cerrar automáticamente':'▶ Abrir automáticamente';$('fluid-toggle').textContent=fluid?'≈ Ocultar agua':'≈ Mostrar agua';$('fluid-toggle').setAttribute('aria-pressed',String(fluid));$('labels-toggle').textContent=showLabels?'⌖ Ocultar etiquetas':'⌖ Mostrar etiquetas';$('opening-value').value=Math.round(opening);$('status').textContent=`Disco ${Math.round(opening)}° · ${opening===0?'válvula cerrada':opening===90?'válvula abierta':'apertura parcial'}`;pipework.visible=mode==='external';pipeCutaway.visible=mode==='internal';flangeGhosts.visible=mode==='internal';fluidGroup.visible=fluid&&mode!=='explode';drawKChart();}
function select(id,focus=true){selected=id;const p=parts.get(id);p.group.visible=true;for(const [key,item] of parts){item.group.traverse(m=>{if(m.isMesh&&m.material.emissive){m.material.emissive.set(key===id?0x7b4010:0x000000);m.material.emissiveIntensity=key===id?.18:0;}});item.button.setAttribute('aria-pressed',String(key===id));}$('part-name').textContent=p.name;$('part-function').textContent=p.func;$('part-effect').textContent=p.effect;$('part-number').textContent=String(catalog.findIndex(x=>x.id===id)+1).padStart(2,'0')+' / 07';if(focus){const box=new THREE.Box3().setFromObject(p.group);const target=box.getCenter(new THREE.Vector3());cameraMove={target,position:target.clone().add(new THREE.Vector3(3,2.2,3).normalize().multiplyScalar(Math.max(3.5,box.getSize(new THREE.Vector3()).length()*1.5)))};}sync();}
for(const [i,data] of catalog.entries()){const p=parts.get(data.id),button=document.createElement('button');button.className='part-row';button.innerHTML=`<span class="num">${String(i+1).padStart(2,'0')}</span><span class="dot" style="background:${data.color}"></span><span>${data.name}</span><span class="arrow">›</span>`;button.onclick=()=>select(data.id);$('parts-list').append(button);p.button=button;const label=document.createElement('button');label.className='part-label';label.textContent=data.name;label.hidden=true;label.onclick=()=>select(data.id);$('labels').append(label);p.label=label;labels.push(p);}
function setMode(next){mode=next;for(const p of parts.values())p.group.visible=true;resetCamera();sync();}
for(const id of ['external','internal','explode'])$(id).onclick=()=>setMode(id);$('assemble').onclick=()=>setMode('external');$('reset').onclick=resetCamera;$('opening').oninput=e=>{opening=Number(e.target.value);auto=false;sync();};$('spin').onclick=()=>{if(!auto){autoDirection=opening>2?-1:1;if(autoDirection>0){fluid=true;mode='internal';resetCamera();}}auto=!auto;sync();};$('fluid-toggle').onclick=()=>{fluid=!fluid;if(fluid){mode='internal';resetCamera();}sync();};$('k-catalog').onchange=e=>{activeKCatalog=e.target.value;drawKChart();};$('labels-toggle').onclick=()=>{showLabels=!showLabels;sync();};$('visibility').onclick=()=>{const p=parts.get(selected);p.group.visible=!p.group.visible;$('visibility').textContent=p.group.visible?'Ocultar pieza':'Mostrar pieza';};$('show-all').onclick=()=>{for(const p of parts.values())p.group.visible=true;$('visibility').textContent='Ocultar pieza';};
renderer.domElement.addEventListener('pointerdown',e=>{const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes,false)[0];if(hit)select(hit.object.userData.component,false);});
const clock=new THREE.Clock();
function animate(){
  requestAnimationFrame(animate);const dt=clock.getDelta();
  if(auto){opening+=dt*6*autoDirection;if(opening>=90||opening<=0){opening=Math.max(0,Math.min(90,opening));auto=false;}$('opening').value=opening;sync();}
  catalogValve.update(opening);
  if(fluid){const openness=Math.max(0,Math.sin(THREE.MathUtils.degToRad(opening)));waterUniforms.uSpeed.value=openness;waterUniforms.uOpacity.value=.12+.07*openness;waterUniforms.uTravel.value+=dt*1.8*openness;for(const bridge of waterPassages){bridge.visible=openness>.02;const radius=.15+.56*openness;bridge.scale.set(radius,radius,.70);bridge.position.y=bridge.userData.side*(.88-.46*openness);}}
  const targetExplode=mode==='explode'?1:0;explode+=((targetExplode-explode)*dt*5);for(const p of parts.values())p.group.position.copy(p.home).addScaledVector(p.offset,explode);const bodyGroup=parts.get('cuerpo').group;if(mode==='internal'){bodyGroup.visible=false;parts.get('asiento').group.visible=false;}else{bodyGroup.visible=true;bodyGroup.traverse(object=>{if(object.isMesh){object.visible=true;object.material.transparent=false;object.material.opacity=1;object.material.depthWrite=true;object.material.wireframe=false;}});parts.get('asiento').group.visible=true;}for(const p of labels){p.label.hidden=!showLabels||!p.group.visible;const v=p.group.getWorldPosition(new THREE.Vector3()).project(camera);p.label.style.left=`${(v.x*.5+.5)*100}%`;p.label.style.top=`${(-v.y*.5+.5)*100}%`;}if(cameraMove){camera.position.lerp(cameraMove.position,Math.min(1,dt*4));controls.target.lerp(cameraMove.target,Math.min(1,dt*4));if(camera.position.distanceTo(cameraMove.position)<.02)cameraMove=null;}controls.update();renderer.setSize(viewport.clientWidth,viewport.clientHeight,false);camera.aspect=viewport.clientWidth/viewport.clientHeight;camera.updateProjectionMatrix();renderer.render(scene,camera);
}
resetCamera();camera.position.copy(cameraMove.position);controls.target.copy(cameraMove.target);cameraMove=null;select('cuerpo',false);$('loading').remove();animate();
